### ISSUE TITLE
Database Deign for Rent API

### ISSUE THREAD

**Issue by davidli8410** [davidli8410/rent-api#1]
We need to confirm the following things:

1. Which database will be used for Rent API 
Some options: mysql, mongodb, dynamodb
2. Database design
3. Database script generated
4. Review the DB

**Comment by johnwalle** [comment]
Well, as far as I concerned, either database is fine. Choose the one you do best.

**Comment by davidli8410** [comment]
We will use Mysql as our Database.
Script will be generated.
