### ISSUE TITLE
Rent API project Setup

### ISSUE THREAD

**Issue by davidli8410** [davidli8410/rent-api#2]
The following we need to confirm first:
1. Which framework we will use?
Spring MVC
2. Which rest framework will we use?
jersey, Spring Restful
3. Deployment
Spring boot, tomcat, jetty
4. Container??
Docker
5. Build tool
Maven

**Comment by johnwalle** [comment]
I prefer Spring MVC

**Comment by zhiyuanMA** [comment]
spring mvc is also a restful framework.

**Comment by davidli8410** [comment]
Develop branch has been added.

**Comment by davidli8410** [comment]
As discussed, the first step will start with following stuff:
1.Maven+ Spring MVC + Mysql
2.Git dev branch created
